name: DimitriPazas
favicon: null
layout_spectrum: 0.7534008231014013
typography_spectrum: 0.8230869884137064
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.36727858893573284
  rhythmicContrast: 0.75
purpose: []
