name: Dimitripazasphotography
favicon: null
layout_spectrum: 0.87501
typography_spectrum: 0.8230869884137064
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fef2fe'
    - '#5b565c'
    - '#feae00'
    - '#003586'
    - '#d0c5d1'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
